packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAgeExclude:
  - '@better-auth/core@1.6.26'
  - '@better-auth/drizzle-adapter@1.6.26'
  - '@better-auth/kysely-adapter@1.6.26'
  - '@better-auth/memory-adapter@1.6.26'
  - '@better-auth/mongo-adapter@1.6.26'
  - '@better-auth/prisma-adapter@1.6.26'
  - '@better-auth/telemetry@1.6.26'
  - '@biomejs/biome@2.5.7'
  - '@biomejs/cli-darwin-arm64@2.5.7'
  - '@biomejs/cli-darwin-x64@2.5.7'
  - '@biomejs/cli-linux-arm64-musl@2.5.7'
  - '@biomejs/cli-linux-arm64@2.5.7'
  - '@biomejs/cli-linux-x64-musl@2.5.7'
  - '@biomejs/cli-linux-x64@2.5.7'
  - '@biomejs/cli-win32-arm64@2.5.7'
  - '@biomejs/cli-win32-x64@2.5.7'
  - better-auth@1.6.26
  - lucide-react@1.53.0
  - '@cloudflare/workers-types@5.20261008.1'
